---
swagger: "2.0"
info:
  x-ibm-name: "jenkins"
  title: "Jenkins"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/jenkins"
consumes:
- "application/xml"
- "application/json"
produces:
- "application/xml"
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
security:
- clientIdHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - invoke:
        target-url: "https://www.youtube.com"
  phase: "realized"
paths:
  /path-1:
    get:
      responses:
        200:
          description: "200 OK"
definitions: {}
tags: []
